### ISSUE TITLE
Getting Map Property to Plugin

### ISSUE THREAD

**Issue by Bobakanoosh** [3331/fly#3]
Hey!

I'm using something similar to this on a project and am trying to pass a value from a map property, set-up as explained in the readme. The only issue is I can't figure out how to access that. I've tried:
`GetEntPropString(entity, Prop_Data, "size", vec, sizeof(vec));`

and other similar things, but nothings worked.

Appreciate any help, let me know if you need more context :)

**Comment by SlidyBat** [comment]
Unfortunately the keyvalues added through a map editor don't make it through to server, since internally they're not really saved as keyvalues, but hardcoded in instead.

However, if you still haven't found another method for doing this and you're intent on using this feature it's very easy for you to search the bsp file to find the value you're looking for.
https://developer.valvesoftware.com/wiki/Source_BSP_File_Format#Entity
The values are pretty much stored in plaintext, so it should be very easy for you to search for the key you're looking for and parse the bsp file to get the value you need.

**Comment by 3331** [comment]
Yep it seems to be hardcoded specifically on the worldspawn entity, maybe we should use another entity as a placeholder for all these custom values?

**Comment by 3331** [comment]
Actually we can just make a custom class and call it `mod_map_info`

**Comment by 3331** [comment]
Hmm seems like that isn't possible either, so at the moment we are looking at custom parsing as the solution unless if I come up with something else..

**Comment by 3331** [comment]
https://github.com/SlidyBat/CustomKeyValues this can be solved with this plugin
